/*
api

Testing ThothEngineModuleAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package UpStudyGoSdk

import (
	"context"
	openapiclient "github.com/UpStudyTeam/UpStudyGoSdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_UpStudyGoSdk_ThothEngineModuleAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ThothEngineModuleAPIService V1BriefAnswersPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ThothEngineModuleAPI.V1BriefAnswersPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThothEngineModuleAPIService V1ShowStepsPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ThothEngineModuleAPI.V1ShowStepsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ThothEngineModuleAPIService V1SingleAnswerPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ThothEngineModuleAPI.V1SingleAnswerPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
