/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package UpStudyGoSdk

import (
	"encoding/json"
)

// checks if the SolverSelfBriefResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SolverSelfBriefResponse{}

// SolverSelfBriefResponse struct for SolverSelfBriefResponse
type SolverSelfBriefResponse struct {
	// User's Latex input
	Input *string `json:"input,omitempty"`
	// All solutions we can provide
	Solutions []SolverSolution `json:"solutions,omitempty"`
}

// NewSolverSelfBriefResponse instantiates a new SolverSelfBriefResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSolverSelfBriefResponse() *SolverSelfBriefResponse {
	this := SolverSelfBriefResponse{}
	return &this
}

// NewSolverSelfBriefResponseWithDefaults instantiates a new SolverSelfBriefResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSolverSelfBriefResponseWithDefaults() *SolverSelfBriefResponse {
	this := SolverSelfBriefResponse{}
	return &this
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *SolverSelfBriefResponse) GetInput() string {
	if o == nil || IsNil(o.Input) {
		var ret string
		return ret
	}
	return *o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolverSelfBriefResponse) GetInputOk() (*string, bool) {
	if o == nil || IsNil(o.Input) {
		return nil, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *SolverSelfBriefResponse) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given string and assigns it to the Input field.
func (o *SolverSelfBriefResponse) SetInput(v string) {
	o.Input = &v
}

// GetSolutions returns the Solutions field value if set, zero value otherwise.
func (o *SolverSelfBriefResponse) GetSolutions() []SolverSolution {
	if o == nil || IsNil(o.Solutions) {
		var ret []SolverSolution
		return ret
	}
	return o.Solutions
}

// GetSolutionsOk returns a tuple with the Solutions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolverSelfBriefResponse) GetSolutionsOk() ([]SolverSolution, bool) {
	if o == nil || IsNil(o.Solutions) {
		return nil, false
	}
	return o.Solutions, true
}

// HasSolutions returns a boolean if a field has been set.
func (o *SolverSelfBriefResponse) HasSolutions() bool {
	if o != nil && !IsNil(o.Solutions) {
		return true
	}

	return false
}

// SetSolutions gets a reference to the given []SolverSolution and assigns it to the Solutions field.
func (o *SolverSelfBriefResponse) SetSolutions(v []SolverSolution) {
	o.Solutions = v
}

func (o SolverSelfBriefResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SolverSelfBriefResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Input) {
		toSerialize["input"] = o.Input
	}
	if !IsNil(o.Solutions) {
		toSerialize["solutions"] = o.Solutions
	}
	return toSerialize, nil
}

type NullableSolverSelfBriefResponse struct {
	value *SolverSelfBriefResponse
	isSet bool
}

func (v NullableSolverSelfBriefResponse) Get() *SolverSelfBriefResponse {
	return v.value
}

func (v *NullableSolverSelfBriefResponse) Set(val *SolverSelfBriefResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSolverSelfBriefResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSolverSelfBriefResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSolverSelfBriefResponse(val *SolverSelfBriefResponse) *NullableSolverSelfBriefResponse {
	return &NullableSolverSelfBriefResponse{value: val, isSet: true}
}

func (v NullableSolverSelfBriefResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSolverSelfBriefResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


