/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package UpStudyGoSdk

import (
	"encoding/json"
)

// checks if the SolverDescription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SolverDescription{}

// SolverDescription struct for SolverDescription
type SolverDescription struct {
	// Descriptive information
	Content *string `json:"content,omitempty"`
	Format *SolverDescriptionFormat `json:"format,omitempty"`
}

// NewSolverDescription instantiates a new SolverDescription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSolverDescription() *SolverDescription {
	this := SolverDescription{}
	return &this
}

// NewSolverDescriptionWithDefaults instantiates a new SolverDescription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSolverDescriptionWithDefaults() *SolverDescription {
	this := SolverDescription{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *SolverDescription) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolverDescription) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *SolverDescription) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *SolverDescription) SetContent(v string) {
	o.Content = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *SolverDescription) GetFormat() SolverDescriptionFormat {
	if o == nil || IsNil(o.Format) {
		var ret SolverDescriptionFormat
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolverDescription) GetFormatOk() (*SolverDescriptionFormat, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *SolverDescription) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given SolverDescriptionFormat and assigns it to the Format field.
func (o *SolverDescription) SetFormat(v SolverDescriptionFormat) {
	o.Format = &v
}

func (o SolverDescription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SolverDescription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	return toSerialize, nil
}

type NullableSolverDescription struct {
	value *SolverDescription
	isSet bool
}

func (v NullableSolverDescription) Get() *SolverDescription {
	return v.value
}

func (v *NullableSolverDescription) Set(val *SolverDescription) {
	v.value = val
	v.isSet = true
}

func (v NullableSolverDescription) IsSet() bool {
	return v.isSet
}

func (v *NullableSolverDescription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSolverDescription(val *SolverDescription) *NullableSolverDescription {
	return &NullableSolverDescription{value: val, isSet: true}
}

func (v NullableSolverDescription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSolverDescription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


