/*
api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package UpStudyGoSdk

import (
	"encoding/json"
)

// checks if the SolverSelfFullResponseText type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SolverSelfFullResponseText{}

// SolverSelfFullResponseText struct for SolverSelfFullResponseText
type SolverSelfFullResponseText struct {
	// User's Latex input
	Input *string `json:"input,omitempty"`
	// All solutions we can provide along with the steps to obtain the solutions
	Solutions []SolverSolutionWithSolvingSteps `json:"solutions,omitempty"`
}

// NewSolverSelfFullResponseText instantiates a new SolverSelfFullResponseText object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSolverSelfFullResponseText() *SolverSelfFullResponseText {
	this := SolverSelfFullResponseText{}
	return &this
}

// NewSolverSelfFullResponseTextWithDefaults instantiates a new SolverSelfFullResponseText object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSolverSelfFullResponseTextWithDefaults() *SolverSelfFullResponseText {
	this := SolverSelfFullResponseText{}
	return &this
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *SolverSelfFullResponseText) GetInput() string {
	if o == nil || IsNil(o.Input) {
		var ret string
		return ret
	}
	return *o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolverSelfFullResponseText) GetInputOk() (*string, bool) {
	if o == nil || IsNil(o.Input) {
		return nil, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *SolverSelfFullResponseText) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given string and assigns it to the Input field.
func (o *SolverSelfFullResponseText) SetInput(v string) {
	o.Input = &v
}

// GetSolutions returns the Solutions field value if set, zero value otherwise.
func (o *SolverSelfFullResponseText) GetSolutions() []SolverSolutionWithSolvingSteps {
	if o == nil || IsNil(o.Solutions) {
		var ret []SolverSolutionWithSolvingSteps
		return ret
	}
	return o.Solutions
}

// GetSolutionsOk returns a tuple with the Solutions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SolverSelfFullResponseText) GetSolutionsOk() ([]SolverSolutionWithSolvingSteps, bool) {
	if o == nil || IsNil(o.Solutions) {
		return nil, false
	}
	return o.Solutions, true
}

// HasSolutions returns a boolean if a field has been set.
func (o *SolverSelfFullResponseText) HasSolutions() bool {
	if o != nil && !IsNil(o.Solutions) {
		return true
	}

	return false
}

// SetSolutions gets a reference to the given []SolverSolutionWithSolvingSteps and assigns it to the Solutions field.
func (o *SolverSelfFullResponseText) SetSolutions(v []SolverSolutionWithSolvingSteps) {
	o.Solutions = v
}

func (o SolverSelfFullResponseText) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SolverSelfFullResponseText) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Input) {
		toSerialize["input"] = o.Input
	}
	if !IsNil(o.Solutions) {
		toSerialize["solutions"] = o.Solutions
	}
	return toSerialize, nil
}

type NullableSolverSelfFullResponseText struct {
	value *SolverSelfFullResponseText
	isSet bool
}

func (v NullableSolverSelfFullResponseText) Get() *SolverSelfFullResponseText {
	return v.value
}

func (v *NullableSolverSelfFullResponseText) Set(val *SolverSelfFullResponseText) {
	v.value = val
	v.isSet = true
}

func (v NullableSolverSelfFullResponseText) IsSet() bool {
	return v.isSet
}

func (v *NullableSolverSelfFullResponseText) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSolverSelfFullResponseText(val *SolverSelfFullResponseText) *NullableSolverSelfFullResponseText {
	return &NullableSolverSelfFullResponseText{value: val, isSet: true}
}

func (v NullableSolverSelfFullResponseText) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSolverSelfFullResponseText) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


